FROM python:slim

WORKDIR /app

EXPOSE 8000

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["gunicorn", "iron_work.wsgi:application", "-b", "0.0.0.0:8000", "-w", "3", "--reload"]