# Generated by Django 4.1.7 on 2024-01-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Заявка',
            new_name='Order',
        ),
    ]
