# Generated by Django 4.1.7 on 2024-01-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_заявка_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='описание',
            new_name='desc',
        ),
    ]
